### ISSUE TITLE
Event times set/stuck to january 1st, 1970

### ISSUE THREAD

**Issue by Zignature** [magtimmermans/com.cyclone-software.sunevents#33]
![Screenshot_20200630-210447](https://user-images.githubusercontent.com/4068757/86166963-fb1e5d80-bb15-11ea-81c4-f015ea0dbf7a.png)

Tomorrow's Night starts, Tomorrow's Night ends, Night starts and Night ends are set/stuck to 1 January 1970 01:00

What can be done about it?
I restarted the app to no avail.

Do I need to uninstall and install again?

Regards,
Siegert

**Comment by dirkg173** [comment]
Hi Siegert,

I had the same question. This is the answer from Marcel:
„The first items is because there is no valid calculation during simmer time. For example the sun in upper north goes not down at all and you will get even less items. Previously I empty those dates but people complain that they could not test it. So now they have Unix timestamp zero. Then you now at least no calc possible.“

**Comment by Zignature** [comment]
Thanks for the explanation 🙂
