### ISSUE TITLE
App "Sunevents" does not work properly if I use "And" condition in a flow

### ISSUE THREAD

**Issue by JWvanSetten** [magtimmermans/com.cyclone-software.sunevents#39]
I try to switch on a lamp with the condition ("And") that this is allowed between 45 minutes before sunset and 45 minutes after sunset. With the card I use "And": Sunevents: It is between Sunset -45 Sunrise tomorrow 45. The strange thing is that this works in the evening but does not work anymore in the morning (until about midnight) I saw that the app Zonnestanden has recently been updated on Nov 30 to 0.6.1, this problem may be due to that, I had the impression that the above just worked at first.
[2020-12-05 App Zonnestanden.docx](https://github.com/magtimmermans/com.cyclone-software.sunevents/files/5652416/2020-12-05.App.Zonnestanden.docx)

**Comment by magtimmermans** [comment]
Hi, This will not work and is removed. The problem is that the Sunset is refreshed to midnight and there for you experience this problem. The problem is complicated as I fix this other parts will fail. Therefore I have removed it in the test version:

https://developer.athom.com/apps/app/com.cyclone-software.sunevents/build/21

**Comment by JWvanSetten** [comment]
Hi, I understand that I cannot use the app in that way. Maybe a warning is in order in the app description. I have now changed the app so that all events occur in one day, between 0:00 and midnight. I think this works, with the same desired result. Thanks for the help and building a really handy app for Homey. Greetings Jan
Now I use is at this way:
https://homey.app/f/cZIJZo
